trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerHubUsername: 'your_dockerhub_username'
  dockerHubPassword: 'your_dockerhub_password'
  aksClusterName: 'tetris-aks-cluster'
  aksNodeCount: 3
  acrName: 'tetrisacr2024'
  aksNodeSize: 'Standard_DS2_v2'

stages:
  - stage: 'DeployInfrastructure'
    displayName: 'Deploy Infrastructure with Terraform'
    jobs:
      - job: 'TerraformJob'
        displayName: 'Terraform Apply'
        steps:
         - script: |
              curl -L -o terraform.zip https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
              unzip terraform.zip
              sudo mv terraform /usr/local/bin/
              terraform --version
           displayName: "Install Terraform Manually"

         - task: AzureCLI@2
           inputs:
                 azureSubscription: 'Azure-Tetris-ServiceConnection'
                 scriptType: 'batch'
                 scriptLocation: 'inlineScript'
                 inlineScript: 'echo "Hello from Azure CLI"'


         - script: |
              terraform init
           displayName: 'Terraform Init'
           workingDirectory: 'IAC_Terraform'

         - script: |
              terraform fmt
              terraform validate
              terraform plan 
           displayName: 'Terraform Plan'
           workingDirectory: 'IAC_Terraform'


