trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerHubUsername: 'your_dockerhub_username'
  dockerHubPassword: 'your_dockerhub_password'
  aksClusterName: 'tetris-aks-cluster'
  aksNodeCount: 3
  acrName: 'tetrisacr2024'
  aksNodeSize: 'Standard_DS2_v2'

stages:
  - stage: 'DeployInfrastructure'
    displayName: 'Deploy Infrastructure with Terraform'
    jobs:
      - job: 'TerraformJob'
        displayName: 'Terraform Apply'
        steps:

        # Install Terraform
        - script: |
            curl -L -o terraform.zip https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
            unzip terraform.zip
            sudo mv terraform /usr/local/bin/
            terraform --version
          displayName: "Install Terraform Manually"

        # AzureCLI Task – includes Terraform
        - task: AzureCLI@2
          displayName: "Terraform Init & Plan"
          inputs:
            azureSubscription: 'Azure-Tetris-ServiceConnection'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo "Logged into Azure"
              az account show

              echo "Exporting Terraform ARM_* variables"
              export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
              export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)
              export ARM_CLIENT_ID=$servicePrincipalId
              export ARM_CLIENT_SECRET=$servicePrincipalKey

              cd IAC_Terraform

              terraform init
              terraform fmt
              terraform validate
              terraform plan
