triggers:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerHubUsername: 'your_dockerhub_username'
  dockerHubPassword: 'your_dockerhub_password'
  aksClusterName: 'tetris-aks-cluster'
  aksNodeCount: 3
  acrName: 'tetrisacr2024'
  aksNodeSize: 'Standard_DS2_v2'

stages:
  - stage: 'DeployInfrastructure'
    displayName: 'Deploy Infrastructure with Terraform'
    jobs:
      - job: 'TerraformJob'
        displayName: 'Terraform Apply'
        steps:
          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.5.7'

          - script: |
              terraform init
            displayName: 'Terraform Init'
            workingDirectory: 'IAC_Terraform'

          - script: |
              terraform apply -auto-approve -var="cluster_name=$(aksClusterName)" -var="node_count=$(aksNodeCount)" -var="acr_name=$(acrName)" -var="node_size=$(aksNodeSize)"
            displayName: 'Terraform Apply'
            workingDirectory: 'IAC_Terraform'
  - stage: 'pull the image'
    displayName: 'Pull the image from DockerHub'
    dependsOn: 'DeployInfrastructure'
    jobs:
      - job: 'PullImageJob'
        displayName: 'Pull Image from DockerHub'
        steps:
          - script: |
              echo "Pulling image from DockerHub..."
              docker login -u $(dockerHubUsername) -p $(dockerHubPassword)
              docker pull $(dockerHubUsername)/tetris:latest
              docker images
              echo "Image pulled successfully."

              echo Tagging and pushing to Azure Container Registry...
              az acr login --name $(acrName)
              docker tag $(dockerHubUsername)/tetris:latest $(acrName).azurecr.io/tetris:latest
              docker push $(acrName).azurecr.io/tetris:latest
            displayName: 'Pull Image'
  - stage: 'Deploy to AKS'
    displayName: 'Deploy Application to AKS'
    dependsOn: 'pull the image'
    jobs:
      - job: 'DeployToAKSJob'
        displayName: 'Deploy to AKS'
        steps:
          - script: |
              echo "Getting AKS credentials..."
              az aks get-credentials --resource-group tetris-rg --name $(aksClusterName)

              echo "Deploying application to AKS..."
              kubectl apply -f k8s/deployment.yaml
              kubectl apply -f k8s/service.yaml

              echo "Deployment completed."
            displayName: 'Deploy to AKS'