apiVersion: v1
kind: Service
metadata:
  name: tetris-service
  labels:
    app: tetris
spec:
  type: LoadBalancer
  selector:
    app: tetris
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      